### PR TITLE
feat: migrate `isExternalLink`

### PR DESCRIPTION
**Pull request by bdbai**
Reference implementation: https://github.com/hexojs/hexo-util/blob/abebca2f89e4d4d6bc319e4c663fd660522fa428/lib/is_external_link.js
Reference test cases: https://github.com/hexojs/hexo-util/blob/abebca2f89e4d4d6bc319e4c663fd660522fa428/test/is_external_link.spec.js

Btw any ideas about what fixture to use for benchmarking?

### CODE REVIEW

**Comment by liby** [comment]
PTAL. 🙏 @Brooooooklyn

**Comment by SukkaW** [comment]
> Btw any ideas about what fixture to use for benchmarking?

IMO we could add the following fixtures:

```
// Internal absolute url
URL: https://hexo.io/docs/
sitehost: https://hexo.io/
// External absolute url
URL: https://example.com/example/
sitehost: https://hexo.io/
// Relative absolute url
URL: /example/
sitehost: https://hexo.io/
```

**Comment by liby** [comment]
That's not good.
```
Running "Internal absolute url" suite...
Progress: 50%

  hexo-util-rs:
    988 949 ops/s, ±1.40% 
Progress: 100%

  hexo-util-rs:
    988 949 ops/s, ±1.40%     | slowest, 70.34% slower

  hexo-util:
    3 334 057 ops/s, ±0.80%   | fastest

Finished 2 cases!
  Fastest: hexo-util
  Slowest: hexo-util-rs
Running "External absolute url" suite...
Progress: 50%

  hexo-util-rs:
    939 688 ops/s, ±0.31% 
Progress: 100%

  hexo-util-rs:
    939 688 ops/s, ±0.31%     | slowest, 69.37% slower

  hexo-util:
    3 067 393 ops/s, ±0.88%   | fastest

Finished 2 cases!
  Fastest: hexo-util
  Slowest: hexo-util-rs
Running "Relative absolute url" suite...
Progress: 50%

  hexo-util-rs:
    1 800 241 ops/s, ±0.62% 
Progress: 100%

  hexo-util-rs:
    1 800 241 ops/s, ±0.62%   | slowest, 45.78% slower

  hexo-util:
    3 320 296 ops/s, ±0.66%   | fastest

Finished 2 cases!
  Fastest: hexo-util
  Slowest: hexo-util-rs
```

**Comment by liby** [comment]
> Shall we add a similar in-memory, string-based cache in hexo-util-rs as well?

cc @SukkaW

**Review by Brooooooklyn — APPROVED** [review]

**Pull request merged**
